name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - clean: dist
      - run: npm ci
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@4.6.3
        with:
          folder: dist
